### ISSUE TITLE
Section about ActiveJob and job processors like Sidekiq or Resque

### ISSUE THREAD

**Issue by skryking** [iJackUA/Ruby-Web-Dev-The-Other-Way#9]
I noticed no mention of background job processors like sidekiq or resque was this on purpose?

**Comment by iJackUA** [comment]
It is because I do not know any big issue with this to write a caution for. 
This is not just another "awesome-ruby" where I list all known gems for any case, but only when I know where to propose less magic solution :)

I could make a section about "ActiveJob" caution and mention job runners there.
If you have any ideas what to cover - suggest please.
